"""Task management handlers - creation, viewing, editing."""

from .filters import (
    view_tasks_menu,
    filter_tasks_created,
    filter_tasks_assigned,
    filter_tasks_select_group,
    filter_tasks_group,
    filter_group_all_tasks,
    filter_tasks_by_assignee,
    filter_tasks_all,
    filter_tasks_archived,
    filter_archived_created,
    filter_archived_assigned,
)

from .creation import (
    create_task,
    task_title_input,
    task_calendar_navigation,
    task_date_selected,
    task_time_selected,
    task_time_manual_input,
    task_description_input,
    # Media functions commented out - step removed from flow
    # task_add_media,
    # task_handle_media_file,
    # task_done_media,
    # task_skip_media,
    task_toggle_user,
    task_confirm_users,
    task_skip_description,
    task_forward_to_date,
    task_forward_to_time,
    task_forward_to_description,
    # task_forward_to_media,  # Commented out - media step removed
    task_forward_to_users,
    task_back_to_title,
    task_back_to_date,
    task_back_to_time,
    task_back_to_description,
    # task_back_to_media,  # Commented out - media step removed
    task_back_to_users,
    cancel_task_creation,
    TASK_STEP_TITLE,
    TASK_STEP_DATE,
    TASK_STEP_TIME,
    TASK_STEP_DESCRIPTION,
    # TASK_STEP_MEDIA,  # Commented out - media step removed
    TASK_STEP_USERS,
)

from .viewing import (
    view_task_detail,
    view_task_media,
)

from .editing import (
    edit_task_handler,
    edit_task_field_handler,
    edit_title_input,
    edit_description_input,
    show_status_edit_menu,
    edit_status_select,
    show_media_edit_menu,
    edit_media_delete,
    delete_media_file,
    edit_media_add,
    handle_edit_media_file,
    show_users_edit_menu,
    edit_toggle_user,
    edit_users_done,
    back_to_edit_menu,
    save_task_changes,
    delete_task_handler,
    delete_task_confirm_handler,
    change_task_status_handler,
    set_task_status_handler,
    EDIT_TASK_MENU,
    EDIT_TASK_TITLE,
    EDIT_TASK_DESCRIPTION,
    EDIT_TASK_MEDIA,
    EDIT_TASK_STATUS,
    EDIT_TASK_USERS,
)

__all__ = [
    # Filters
    'view_tasks_menu',
    'filter_tasks_created',
    'filter_tasks_assigned',
    'filter_tasks_select_group',
    'filter_tasks_group',
    'filter_group_all_tasks',
    'filter_tasks_by_assignee',
    'filter_tasks_all',
    'filter_tasks_archived',
    'filter_archived_created',
    'filter_archived_assigned',
    # Creation + conversation states
    'create_task',
    'task_title_input',
    'task_calendar_navigation',
    'task_date_selected',
    'task_time_selected',
    'task_time_manual_input',
    'task_description_input',
    'task_add_media',
    'task_handle_media_file',
    'task_done_media',
    'task_skip_media',
    #'select_users_for_task',
    'task_toggle_user',
    'task_confirm_users',
    'task_skip_description',
    'task_forward_to_date',
    'task_forward_to_time',
    'task_forward_to_description',
    'task_forward_to_media',
    'task_forward_to_users',
    'task_back_to_title',
    'task_back_to_date',
    'task_back_to_time',
    'task_back_to_description',
    'task_back_to_media',
    'task_back_to_users',
    'cancel_task_creation',
    'TASK_STEP_TITLE',
    'TASK_STEP_DATE',
    'TASK_STEP_TIME',
    'TASK_STEP_DESCRIPTION',
    'TASK_STEP_MEDIA',
    'TASK_STEP_USERS',
    # Viewing
    'view_task_detail',
    'view_task_media',
    # Editing
    'edit_task_handler',
    'edit_task_field_handler',
    'edit_title_input',
    'edit_description_input',
    'show_status_edit_menu',
    'edit_status_select',
    'show_media_edit_menu',
    'edit_media_delete',
    'delete_media_file',
    'edit_media_add',
    'handle_edit_media_file',
    'show_users_edit_menu',
    'edit_toggle_user',
    'edit_users_done',
    'back_to_edit_menu',
    'save_task_changes',
    'delete_task_handler',
    'delete_task_confirm_handler',
    'change_task_status_handler',
    'set_task_status_handler',
    'EDIT_TASK_MENU',
    'EDIT_TASK_TITLE',
    'EDIT_TASK_DESCRIPTION',
    'EDIT_TASK_MEDIA',
    'EDIT_TASK_STATUS',
    'EDIT_TASK_USERS',
]
